### ISSUE TITLE
Double-check 'cut selection' works

### ISSUE THREAD

**Issue by raboof** [codelv/inkcut#104]
I just tried to use 'cut selection' from the inkscape plugin, and it opened an empty document in Inkcut. Don't have time to check whether this is a problem with my setup or with Inkcut right now, but 'Open current document' works fine.

**Comment by frmdstryr** [comment]
Probably https://github.com/codelv/inkcut/pull/101

**Comment by frmdstryr** [comment]
Merged #101 , reopen if there's issues.
