### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by frmdstryr** [codelv/inkcut#13]
Please submit any feature requests you would like to see in the new version.

Some features I have at the moment (many are still a WIP and will change)

Recent jobs panel
![peek 2017-12-15 10-02](https://user-images.githubusercontent.com/380158/34048264-17498758-e181-11e7-9304-f4f14181463d.gif)

Device control panel
![peek 2017-12-15 09-53](https://user-images.githubusercontent.com/380158/34047637-e5a1389c-e17e-11e7-8384-d58b544274fa.gif)

Thanks!

**Comment by matthijskooijman** [comment]
See also https://github.com/slandis/InkCutter/issues

**Comment by frmdstryr** [comment]
I believe all of those are fixed in this release.

The only thing that is not done is automatic text conversion (rects and groups are now supported). It maybe will be added in the future.


![peek 2017-12-15 09-41](https://user-images.githubusercontent.com/380158/34046793-35cd1398-e17c-11e7-8214-d758581cf18e.gif)

**Comment by frmdstryr** [comment]
A request was made to have different translations.

I am also adding Python 3 and Qt5 support (as it is no longer using gtk).

**Comment by raboof** [comment]
Maybe we should close this one and ask people to submit separate wishlist issues?
