### ISSUE TITLE
I'm confused on status of inkcut

### ISSUE THREAD

**Issue by ilenedream** [codelv/inkcut#139]
What is the status on inkcut for windows or ios? 
I don't see a download link, did see the help needed notation.

Thanks
I

**Comment by frmdstryr** [comment]
A few users have reported it works on both platforms. The install process is the same as long as python is available on the system

I only develop and test on Linux so I was hoping someone would contribute to the documentation for other platforms.

**Comment by ilenedream** [comment]
I don’t know what python is. 🧐

Ilene
