### ISSUE TITLE
Swap X / Y axle

### ISSUE THREAD

**Issue by anITiot** [codelv/inkcut#140]
![screenshot - 2019-02-22 16_19_41](https://user-images.githubusercontent.com/41759653/53254452-aec24280-36c3-11e9-87f5-01963f639599.png)
Is it possible to have a checkbox for alter the x/y settings, I think its easier to have the orientation on the screen compared to the plotter and no need for mirror the object.
Now I need to have the settings in "Device setup" Device, Output, Rotation 90 X=1 Y=-1.

**Comment by frmdstryr** [comment]
Yes I can add a swap x y option there

**Comment by frmdstryr** [comment]
Added in https://github.com/codelv/inkcut/commit/cc5a155e293865f42df7ced0f128466119eace3f

**Comment by lawrence-jeff** [comment]
@frmdstryr  I know this is a closed issue, but does this swap option not work using the control tab? My device (Vinyl Express/Redsail) has the axis swapped and no matter what setting I use the jog commands are still flipped. If I setup two identical devices one with the flip x/y enabled and one without and test using both the jog commands seem in both cases to send the same commands (i.e. it doesn't flip the values depending on profile).

Just getting started with the software so want to make sure its working as expected first.. maybe the control code doesn't respect this setting but actual printing does?
