### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by JackThomasStone** [codelv/inkcut#142]
An error prevented startup. This is either a bug or a required library is missing on your system. 

and only one is imported per session.

    Currently-imported Qt library:   'pyqt5'
    PyQt4 installed:                 False
    PyQt5 installed:                 False
    PySide >= 1.0.3 installed:       False
    PySide2 installed:               False
    Tried to load:                   ['pyqt5']
    
Loading from IPython < 4.0 failed with: No module named 'IPython.qt.console.rich_ipython_widget'

Please report this issue or request help at https://github.com/codelv/inkcut

**Comment by frmdstryr** [comment]
Try `pip3 install pyqt5`

**Comment by JackThomasStone** [comment]
> Try `pip3 install pyqt5`

Worked. Thank you! :-)

**Comment by frmdstryr** [comment]
:+1:
