### ISSUE TITLE
Unable to connect to cutter

### ISSUE THREAD

**Issue by shortcircuit48** [codelv/inkcut#19]
When I attempt to plot drawing I get 
Traceback (most recent call last):
  File "/home/hamish/inkcut-master/inkcut/device/manifest.enaml", line 45, in job_start
    yield defer.maybeDeferred(plugin.submit, job)
TypeError: <lambda>() missing 1 required positional argument: 'info'
How do I overcome?

**Comment by frmdstryr** [comment]
Can you attach the log here (drag and drop) so I can see where this is occurring.

Thanks!

**Comment by frmdstryr** [comment]
https://github.com/codelv/inkcut/commit/4f3be0f749327ad13db9424ef0f4ec84cea40490
