### ISSUE TITLE
Path optimization

### ISSUE THREAD

**Issue by raboof** [codelv/inkcut#26]
(low-prio feature) for larger cuts it might be nice to optimize the path with a technique like the one used in https://github.com/inconvergent/svgsort

**Comment by frmdstryr** [comment]
I took a shot at this in #123. 

The shortest path algorithm could be improved. It's currently using a sort of spin off of [Dijkstra's algorithm](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm). I haven't tested it for very large number of subpaths but it time limits the search to 200ms.  Seems to work alright.

**Comment by frmdstryr** [comment]
Merged. Feel free to add a PR if you come up with a better or another way to optimize paths.
