### ISSUE TITLE
macOS operation

### ISSUE THREAD

**Issue by jmansour** [codelv/inkcut#29]
Hi there

Just FYI, I have this up and running on macOS High Sierra & Python 3.6. I simply pulled out the checks for Darwin platform, and it fires up just fine. 

Communication with my cutter (PCut CT1200) is pretty flakey, and there are a few other issues as expected, but it's a start. 

I'm guessing OSX isn't a high priority for you, but if you'd like me to log issues here I can. 

thanks.

**Comment by frmdstryr** [comment]
Hi, good to hear! Yeah, logging them here its fine. 

My time is going to be limited the next few months but I do have a MacBook and can help with any issues you find.
