### ISSUE TITLE
Configure 'output scale' from DeviceDriver manifests

### ISSUE THREAD

**Issue by raboof** [codelv/inkcut#56]
For example, it seems the correct value for the Silhouette Portrait is 5.64 (since 200 dots is 1 cm on this device).

**Comment by frmdstryr** [comment]
Good idea. It would be easiest to add a `default_config = d_(Dict())` to the DeviceDriver and then make the factory take a dict as it's first argument with the default config.

**Comment by raboof** [comment]
fixed in #63
