### ISSUE TITLE
Metric vs imperial measurements?

### ISSUE THREAD

**Issue by raboof** [codelv/inkcut#61]
We seem to use inches in some places and mm/cm in others. Would it be good to standardize on one or the other? Or would it even be feasible to make it configurable?

**Comment by frmdstryr** [comment]
The UI should be configurable. I believe the option is in the code but I never got around to making a "Preferences" view.

Regarding the inconsistencies, are you referring to the DeviceDrivers?

**Comment by raboof** [comment]
Yes I guess that was in the DeviceDrivers.

Having this configurable would be cool to look into!

**Comment by frmdstryr** [comment]
Added in https://github.com/codelv/inkcut/commit/aec7d6ab65dd69df1852b09871dffb53a39b746a
