### ISSUE TITLE
Crash when resize material if design too big

### ISSUE THREAD

**Issue by srdco** [codelv/inkcut#88]
Inkcut aborts without message when you try to resize material if the design is bigger than the new size.

Steps to recreate (with current inkcut/master):
1) Open a design
2) Click on Material, and set a width that is smaller than the graphic size
As soon as you tab, enter, or click out of the width box, Inkcut aborts.

Easy workaround is to resize the design smaller before you change the material size...

Also, is there no way to clear the work area back to a blank slate?

**Comment by srdco** [comment]
Also, clicking "Read from Device" (with Vision Engraver selected, at least), causes an instant abort as well - even if the graphic size is small enough.

And ... I realized File --> Close clears the work area.

**Comment by frmdstryr** [comment]
Thanks, I'll push an update to fix this. 
 
Regarding the "Read from Device" error, I'm going to remove this from the UI for now as it's not yet implemented. My device doesn't support it so I can't test it here, but I would like to add this for devices that do.  If someone knows what command is used to query the device retrieve this, that would be great!

**Comment by frmdstryr** [comment]
This is now merged. If you get a chance try it out and let me know if you find any other issues.

**Comment by srdco** [comment]
Just updated and tested it. Works great - Thanks!
