### ISSUE TITLE
Project needs to be mentioned on Inkscape's website

### ISSUE THREAD

**Issue by Moini** [codelv/inkcut#91]
Hi there,

this project definitely needs to make it into the list at 
https://inkscape.org/en/gallery/=extension/ !

Can you make an account at inkscape.org and add a link to your website and extension?
Please also add the corresponding tags (follow link in description of linked page to learn how), to present it as well as possible.

Thanks!

**Comment by raboof** [comment]
I guess we might first want to make a release (#78) and provide easy-to-follow installation instructions - but yes, agreed!

**Comment by Moini** [comment]
Sounds good to me :-D

**Comment by frmdstryr** [comment]
Thank you for creating this issue. 

I added the Inkcut for Inkscape extension to their extension list [here](https://inkscape.org/en/~frmdstryr/%E2%98%85inkcut). 

I assume it must be approved or something before it goes live onto the extension page?

**Comment by Moini** [comment]
Thank you! I'm not sure for how long the gallery pages are cached, but that might explain if it took a couple of minutes to show in the list.
