### ISSUE TITLE
How to handle the cups server not being available

### ISSUE THREAD

**Issue by raboof** [codelv/inkcut#99]
When there is no cups server running, inkcut could crash trying to enumerate the printer.

Interestingly this happens sometimes but not all of the time when running the tests on Travis.

How do we want inkcut to behave when there is no cups server running? I guess the simplest solution is to write a warning to the logging and return an empty list of printers?

**Comment by frmdstryr** [comment]
Yes, just a try  / except should be sufficient.

**Comment by frmdstryr** [comment]
I saw this in travis and added the above commit as a workaround. Please reopen if the problem still exists.
